function cellInfo = bus_SL_OUT(varargin) 
suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'SL_OUT_type', ... 
    'SL_func.h', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'ctrl_state', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'q_deg', 5, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'qd_degs', 5, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'q_des_deg', 36, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'qd_des_degs', 36, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
