function cellInfo = bus_SL_IN(varargin) 
suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'SL_IN_type', ... 
    'SL_func.h', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
%{'state', 1, 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
%{'param_D', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
%{'param_K', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
%{'q_set', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
%{'qd_set', 2, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'p_d_bar', 10, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'t_sol_s', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
} ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
